services:
  - type: web
    name: client-dashboard-bot
    env: python
    plan: free
    buildCommand: python3 -m pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
